																 							 /*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module scm_45 #(parameter nbits = 32, fraccion=20) (	
    A,
    out1,
	clk,
	rst
);


 // Port mode declarations:
  input clk, rst;
  input  signed  [nbits-1:0] A;
  output reg  [nbits-1:0] out1;
  

  //Multipliers:

  wire signed [nbits+fraccion-1:0]
    w1,
    w4,
    w3,
    w48,
    w45,
    w47185920;

  assign w1 = A;
  assign w4 = w1 << 2;
  assign w3 = w4 - w1;
  assign w48 = w3 << 4;
  assign w45 = w48 - w3;
  assign w47185920 = w45 << 20;

 
  
  
  always @(posedge clk or negedge rst) begin
	  	if (!rst) begin
		  out1 <= {nbits{1'b0}};
	  	end
	  	else begin

  		  out1 <= w47185920[nbits+fraccion-1:fraccion];
			
		end
   end


endmodule //multiplier_block
