																 						  																 							 /*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module scm_0p001 #(parameter nbits = 32, fraccion=20) (	
    A,
    out1,
	clk,
	rst
);


 // Port mode declarations:
  input clk, rst;
  input  signed  [nbits-1:0] A;
  output reg  [nbits-1:0] out1;
  

  //Multipliers:

  wire signed [nbits+fraccion-1:0]
    w1,
    w128,
    w129,
    w2,
    w131,
    w1048;

  assign w1 = A;
  assign w128 = w1 << 7;
  assign w129 = w1 + w128;
  assign w2 = w1 << 1;
  assign w131 = w129 + w2;
  assign w1048 = w131 << 3;
					  
  
  always @(posedge clk or negedge rst) begin
	  	if (!rst) begin
		  out1 <= {nbits{1'b0}};
	  	end
	  	else begin

  		  out1 <= w1048[nbits+fraccion-1:fraccion];
			
		end
   end


endmodule //multiplier_block
