									 						  																 							 /*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module scm_64 #(parameter nbits = 32, fraccion=20) (	
    A,
    out1,
	clk,
	rst
);


 // Port mode declarations:
  input clk, rst;
  input  signed  [nbits-1:0] A;
  output reg  [nbits-1:0] out1;
  

  //Multipliers:

  wire signed [nbits+fraccion-1:0]
    w1,
    w67108864;

  assign w1 = A;
  assign w67108864 = w1 << 26;
					   

  
  always @(posedge clk or negedge rst) begin
	  	if (!rst) begin
		  out1 <= {nbits{1'b0}};
	  	end
	  	else begin

  		  out1 <= w67108864[nbits+fraccion-1:fraccion];
			
		end
   end


endmodule //multiplier_block
