							   														   																																													 							 /*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module scm_div4factorial #(parameter nbits = 32, fraccion=20) (	
    A,
    out1,
	clk,
	rst
);


 // Port mode declarations:
  input clk, rst;
  input  signed  [nbits-1:0] A;
  output reg  [nbits-1:0] out1;
  

  //Multipliers:

  wire signed [nbits+fraccion-1:0]
    w1,
    w4096,
    w4097,
    w16388,
    w16387,
    w64,
    w65,
    w8,
    w57,
    w1824,
    w14563,
    w58252,
    w43689;

  assign w1 = A;
  assign w4096 = w1 << 12;
  assign w4097 = w1 + w4096;
  assign w16388 = w4097 << 2;
  assign w16387 = w16388 - w1;
  assign w64 = w1 << 6;
  assign w65 = w1 + w64;
  assign w8 = w1 << 3;
  assign w57 = w65 - w8;
  assign w1824 = w57 << 5;
  assign w14563 = w16387 - w1824;
  assign w58252 = w14563 << 2;
  assign w43689 = w58252 - w14563;

  					  
  
  always @(posedge clk or negedge rst) begin
	  	if (!rst) begin
		  out1 <= {nbits{1'b0}};
	  	end
	  	else begin

  		  out1 <= w43689[nbits+fraccion-1:fraccion];
			
		end
   end


endmodule //multiplier_block
