														   																																													 							 /*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module scm_div3factorial #(parameter nbits = 32, fraccion=20) (	
    A,
    out1,
	clk,
	rst
);


 // Port mode declarations:
  input clk, rst;
  input  signed  [nbits-1:0] A;
  output reg  [nbits-1:0] out1;
  

  //Multipliers:

  wire signed [nbits+fraccion-1:0]
    w1,
    w2048,
    w2047,
    w32768,
    w34815,
    w16,
    w17,
    w136,
    w34951,
    w139804,
    w174755;

  assign w1 = A;
  assign w2048 = w1 << 11;
  assign w2047 = w2048 - w1;
  assign w32768 = w1 << 15;
  assign w34815 = w2047 + w32768;
  assign w16 = w1 << 4;
  assign w17 = w1 + w16;
  assign w136 = w17 << 3;
  assign w34951 = w34815 + w136;
  assign w139804 = w34951 << 2;
  assign w174755 = w34951 + w139804;


  
  always @(posedge clk or negedge rst) begin
	  	if (!rst) begin
		  out1 <= {nbits{1'b0}};
	  	end
	  	else begin

  		  out1 <= w174755[nbits+fraccion-1:fraccion];
			
		end
   end


endmodule //multiplier_block
